/** Database adapter and forward-only schema migrations.
 * PostgreSQL is the sole transactional store, per the approved architecture
 * (API: auth/commands/read models; PostgreSQL: durable state/audit/risk).
 */
import { readLocalPostgresConfiguration } from "./local-database.js";
import pg from "pg";
import { databaseTlsOptions } from "../production-config.js";

export const SCHEMA_VERSION = 13;

type Parameter = string | number | boolean | null;
export type Query = <T = Record<string, unknown>>(
  sql: string,
  params?: Parameter[],
) => Promise<T[]>;
export interface Store {
  transaction<T>(fn: (query: Query) => Promise<T>): Promise<T>;
  close(): Promise<void>;
}

/** Open one PostgreSQL pool. Local configuration is generated by ensureLocalPostgres;
 * production requires an explicit DATABASE_URL. No alternate database engine exists here.
 */
export function openDatabaseStore(
  url = process.env.DATABASE_URL ||
    (process.env.NODE_ENV !== "production"
      ? readLocalPostgresConfiguration()?.applicationUrl
      : undefined),
): Store {
  if (!url || !/^postgres(?:ql)?:\/\//.test(url)) {
    throw new Error(
      "A PostgreSQL DATABASE_URL is required. Run `npm run db:setup --workspace backend/nodejs` to initialize local PostgreSQL.",
    );
  }
  const pool = new pg.Pool({
    ...databaseTlsOptions(url),
    max: 5,
    connectionTimeoutMillis: 5000,
    idleTimeoutMillis: 30000,
    statement_timeout: 20000,
    query_timeout: 25000,
    idle_in_transaction_session_timeout: 20000,
  });
  pool.on("error", () =>
    console.error("Database idle connection failed; pool will replace it."),
  );
  return {
    /** Commit the callback atomically; rollback failures discard the connection so a
     * corrupted transaction state is never reused by the next borrower. */
    async transaction(fn) {
      let client: pg.PoolClient | null = null;
      let broken = true;
      try {
        client = await pool.connect();
        const query: Query = async <T>(
          sql: string,
          params: Parameter[] = [],
        ): Promise<T[]> => (await client!.query(sql, params)).rows as T[];
        await query("BEGIN");
        broken = false;
        try {
          const value = await fn(query);
          await query("COMMIT");
          return value;
        } catch (error) {
          try {
            await query("ROLLBACK");
          } catch {
            broken = true;
          }
          throw error;
        }
      } finally {
        client?.release(broken);
      }
    },
    async close() {
      await pool.end();
    },
  };
}

/** Apply each numbered schema change once, under an advisory lock so concurrent
 * startups (dev + test) never race the same migration. The runtime role gets DML
 * privileges only on the tables it needs; migration credentials (the admin
 * connection this runs under) are never given to the running API. */
export async function runDatabaseMigrations(
  store: Store,
  options: { runtimePassword?: string | undefined; runtimeRole?: string } = {
    runtimePassword: process.env.APP_DATABASE_PASSWORD,
  },
) {
  await store.transaction(async (query) => {
    await query("SELECT pg_advisory_xact_lock(9284001)");
    await query(
      "CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY)",
    );
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=1"))
        .length
    ) {
      await query(
        `CREATE TABLE market_calendar (
           exchange VARCHAR(10) NOT NULL,
           segment VARCHAR(10) NOT NULL,
           trading_day DATE NOT NULL,
           is_trading_day BOOLEAN NOT NULL,
           closure_reason TEXT,
           pre_open_start TIMESTAMPTZ,
           market_open TIMESTAMPTZ,
           market_close TIMESTAMPTZ,
           PRIMARY KEY (exchange, segment, trading_day)
         )`,
      );
      await query("INSERT INTO schema_migrations (version) VALUES (1)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=2"))
        .length
    ) {
      await query(
        `CREATE TABLE broker_app_credentials (
           workspace_id VARCHAR(64) NOT NULL,
           provider VARCHAR(20) NOT NULL,
           ciphertext TEXT NOT NULL,
           updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
           PRIMARY KEY (workspace_id, provider)
         )`,
      );
      await query("INSERT INTO schema_migrations (version) VALUES (2)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=3"))
        .length
    ) {
      await query(
        `CREATE TABLE broker_sessions (
           workspace_id VARCHAR(64) NOT NULL,
           provider VARCHAR(20) NOT NULL,
           ciphertext TEXT NOT NULL,
           expires_at TIMESTAMPTZ NOT NULL,
           updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
           PRIMARY KEY (workspace_id, provider)
         )`,
      );
      await query("INSERT INTO schema_migrations (version) VALUES (3)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=4"))
        .length
    ) {
      await query(
        `CREATE TABLE users (
           id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
           email VARCHAR(320) NOT NULL UNIQUE,
           password_hash TEXT NOT NULL,
           created_at TIMESTAMPTZ NOT NULL DEFAULT now()
         )`,
      );
      await query(
        `CREATE TABLE sessions (
           token_hash CHAR(64) PRIMARY KEY,
           user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
           expires_at TIMESTAMPTZ NOT NULL,
           created_at TIMESTAMPTZ NOT NULL DEFAULT now()
         )`,
      );
      await query("CREATE INDEX sessions_user_id_idx ON sessions(user_id)");
      await query("INSERT INTO schema_migrations (version) VALUES (4)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=5"))
        .length
    ) {
      // Replaces the in-memory pending-Zerodha-OAuth Map: a JS Map is
      // process-local, so it's lost on restart and doesn't work across
      // replicas -- a valid callback routed to a different replica than the
      // one that issued the state would be rejected as "never issued".
      // Only the state's SHA-256 hash is stored, matching sessions'
      // token_hash pattern: a database dump alone can't be replayed as a
      // valid OAuth state.
      await query(
        `CREATE TABLE zerodha_oauth_state (
           state_hash CHAR(64) PRIMARY KEY,
           workspace_id VARCHAR(64) NOT NULL,
           created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
           expires_at TIMESTAMPTZ NOT NULL
         )`,
      );
      await query("INSERT INTO schema_migrations (version) VALUES (5)");
    }
    if (
      !(await query("SELECT version FROM schema_migrations WHERE version=6"))
        .length
    ) {
      // Tracks which holiday-calendar source/version last seeded each
      // exchange/segment's market_calendar rows -- see market-calendar.ts's
      // seedNseCalendar. Makes provenance inspectable instead of only
      // implied by whenever seeding happened to run.
      await query(
        `CREATE TABLE calendar_metadata (
           exchange VARCHAR(10) NOT NULL,
           segment VARCHAR(10) NOT NULL,
           source TEXT NOT NULL,
           version TEXT NOT NULL,
           imported_at TIMESTAMPTZ NOT NULL,
           PRIMARY KEY (exchange, segment)
         )`,
      );
      await query("INSERT INTO schema_migrations (version) VALUES (6)");
    }
    if (!(await query("SELECT version FROM schema_migrations WHERE version=7")).length) {
      // Public source headlines only. Never store workspace/account events here.
      await query(`CREATE TABLE alpha_wire_items (
        id TEXT PRIMARY KEY, payload JSONB NOT NULL, received_at TIMESTAMPTZ NOT NULL DEFAULT now()
      )`);
      await query("CREATE INDEX alpha_wire_received_idx ON alpha_wire_items(received_at DESC)");
      await query("INSERT INTO schema_migrations (version) VALUES (7)");
    }
    if (!(await query("SELECT version FROM schema_migrations WHERE version=8")).length) {
      await query("CREATE TABLE alpha_wire_poll_state (provider TEXT PRIMARY KEY, next_poll_at TIMESTAMPTZ NOT NULL)");
      await query("INSERT INTO schema_migrations (version) VALUES (8)");
    }
    if (!(await query("SELECT version FROM schema_migrations WHERE version=9")).length) {
      // Legacy rows remain unowned: never overwrite a possible manual override.
      await query("ALTER TABLE market_calendar ADD COLUMN managed_version TEXT");
      await query("INSERT INTO schema_migrations (version) VALUES (9)");
    }
    if (!(await query("SELECT version FROM schema_migrations WHERE version=10")).length) {
      await query(`CREATE TABLE account_access_codes (
        token_hash CHAR(64) PRIMARY KEY,
        email VARCHAR(254) NOT NULL,
        purpose TEXT NOT NULL CHECK (purpose IN ('invite','reset')),
        password_version TEXT,
        expires_at TIMESTAMPTZ NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE(email,purpose)
      )`);
      await query("INSERT INTO schema_migrations (version) VALUES (10)");
    }
    if (!(await query("SELECT version FROM schema_migrations WHERE version=11")).length) {
      // One row per workspace per completed trading day -- see
      // session-performance.ts. gross_paise only: chargesPaise is still
      // unknown for every provider, so there is no true net figure to
      // record either (same reasoning as panels.ts's PnlDataSchema).
      await query(`CREATE TABLE session_pnl_history (
        workspace_id VARCHAR(64) NOT NULL,
        trading_day DATE NOT NULL,
        gross_paise BIGINT NOT NULL,
        recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (workspace_id, trading_day)
      )`);
      await query("INSERT INTO schema_migrations (version) VALUES (11)");
    }
    if (!(await query("SELECT version FROM schema_migrations WHERE version=12")).length) {
      // Rows recorded before coverage was enforced are preserved for audit,
      // but excluded from statistics until a fully reconciled snapshot
      // explicitly replaces them.
      await query("ALTER TABLE session_pnl_history ADD COLUMN coverage_key TEXT");
      await query("INSERT INTO schema_migrations (version) VALUES (12)");
    }
    if (!(await query("SELECT version FROM schema_migrations WHERE version=13")).length) {
      // One-time reconciliation: alpha_wire_items.id is a hash of the item's
      // own display title, so a title-formatting fix (a dedup-key change, a
      // display-text correction) mints a new id for an announcement already
      // stored under the old wording -- the old row never self-heals, since
      // inserts are ON CONFLICT DO NOTHING. This marks rows that are the
      // same underlying announcement (same source, same publish timestamp,
      // same title once formatting/punctuation is stripped) as superseded,
      // keeping only the most recently received one -- which carries the
      // current, corrected text -- visible. Marking rather than deleting
      // keeps the reconciliation reversible and auditable.
      await query("ALTER TABLE alpha_wire_items ADD COLUMN superseded BOOLEAN NOT NULL DEFAULT false");
      await query(`
        UPDATE alpha_wire_items SET superseded = true WHERE id IN (
          SELECT id FROM (
            SELECT id, ROW_NUMBER() OVER (
              PARTITION BY payload->>'source', payload->>'publishedAt',
                lower(regexp_replace(payload->>'title', '[^a-z0-9]+', '', 'gi'))
              ORDER BY received_at DESC, id DESC
            ) AS rank
            FROM alpha_wire_items
          ) ranked WHERE rank > 1
        )
      `);
      await query("INSERT INTO schema_migrations (version) VALUES (13)");
    }
    if (options.runtimePassword || options.runtimeRole) {
      if (options.runtimeRole && options.runtimeRole !== "nraialgo_app") throw new Error("Unsupported runtime database role");
      const password = options.runtimePassword;
      if (
        !(
          await query("SELECT rolname FROM pg_roles WHERE rolname='nraialgo_app'")
        ).length
      ) {
        if (!password) throw new Error("Create the nraialgo_app user in DigitalOcean before migrating");
        await query(
          "CREATE ROLE nraialgo_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE",
        );
      }
      // ALTER ROLE needs a SQL literal. Do not assume supplied deployment
      // passwords contain only alphanumeric characters.
      await query("SET LOCAL standard_conforming_strings = on");
      if (password) await query(`ALTER ROLE nraialgo_app PASSWORD '${password.replaceAll("'", "''")}'`);
      // Use a dedicated application database. Remove default schema creation
      // privileges, including PUBLIC's inherited grant on older PostgreSQL.
      await query("REVOKE CREATE ON SCHEMA public FROM PUBLIC");
      await query("REVOKE ALL ON SCHEMA public FROM nraialgo_app");
      await query("REVOKE ALL ON schema_migrations FROM nraialgo_app");
      await query("GRANT USAGE ON SCHEMA public TO nraialgo_app");
      await query(
        "GRANT SELECT,INSERT,UPDATE,DELETE ON market_calendar,broker_app_credentials,broker_sessions,users,sessions,zerodha_oauth_state,calendar_metadata,alpha_wire_items,alpha_wire_poll_state,session_pnl_history TO nraialgo_app",
      );
      // Read-only: the running API reports the schema version (/v1/readiness)
      // but must never itself apply a migration -- INSERT/UPDATE/DELETE here
      // stay ungranted deliberately.
      await query("GRANT SELECT ON schema_migrations TO nraialgo_app");
      // Only the offline administrator may issue codes; the API can redeem them.
      await query("REVOKE ALL ON account_access_codes FROM nraialgo_app");
      await query("GRANT SELECT,DELETE ON account_access_codes TO nraialgo_app");
    }
  });
}

export async function verifyRuntimeDatabase(store: Store) {
  await store.transaction(async query => {
    const [version] = await query<{ max: number | null }>("SELECT MAX(version) as max FROM schema_migrations");
    if (version?.max !== SCHEMA_VERSION) throw new Error("Database schema is not compatible; run the release migration first");
    const [role] = await query<{ safe: boolean }>(`SELECT (current_user = 'nraialgo_app'
      AND NOT rolsuper AND NOT rolcreatedb AND NOT rolcreaterole AND NOT rolbypassrls
      AND NOT has_schema_privilege(current_user, 'public', 'CREATE')
      AND NOT has_table_privilege(current_user, 'schema_migrations', 'INSERT,UPDATE,DELETE')) AS safe
      FROM pg_roles WHERE rolname = current_user`);
    if (!role?.safe) throw new Error("Runtime database role is overprivileged");
  });
}
